name: Bug Report
description: Something isn't working quite right in the software.
body:
- type: markdown
  attributes:
    value: |
      Bug reports should only be used for reporting issues with how the software works. For assistance installing this software, as well as debugging issues with dependencies, please use our [Discord server](https://discord.gg/VJfAaqVGs7).

- type: textarea
  attributes:
    label: Current Behavior
    description: Please provide a clear & concise description of the issue.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    description: Please describe what you expected to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to Reproduce
    description: Please be as detailed as possible when providing steps to reproduce, failure to provide steps will result in this issue being closed.
  validations:
    required: true

- type: input
  id: panel-version
  attributes:
    label: Panel Version
    description: Version number of your Panel ("latest" is not a version)
    placeholder: 1.12.0
  validations:
    required: true

- type: input
  id: floe-version
  attributes:
    label: Floe Version
    description: Version number for Floe ("latest" is not a version)
    placeholder: 1.12.0
  validations:
    required: true
