blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://discord.gg/VJfAaqVGs7
    about: Please visit our Discord for general questions about Pterodactyl.
  - name: Feature Request
    about: We are not currently accepting feature requests for this software due to developer time constraints.
