name: docker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
jobs:
  push:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'main') || (!contains(github.event.head_commit.message, 'skip docker') && !contains(github.event.head_commit.message, 'docker skip'))"
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/belugabit-io/panel
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'release' && github.event.action == 'published' && github.event.release.prerelease == false }}
            type=ref,event=tag
            type=ref,event=branch

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: "github.event_name != 'pull_request'"
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - if: "github.event_name == 'release' && github.event.action == 'published'"
        env:
          REF: ${{ github.event.release.tag_name }}
        run: |
          sed -i "s/    'version' => 'canary',/    'version' => '${REF:1}',/" config/app.php
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
